cf-cli/cf-linux64:
  size: 19896417
  object_id: 1e711010-7c7c-4852-b32b-924e195fb1c6
  sha: 1ab6a9c11d92cf7fb443c24225a007b6fcb3cc99
cfdot/cfdot-linux64:
  size: 15276752
  object_id: 13ff04cf-4de5-4615-5e77-6860345e732f
  sha: cfeb01157febcf5f954631795c1db76a7fa59856
esuf/esuf-linux-amd64:
  size: 8293096
  object_id: 0926492c-2b17-4bc8-b5e5-5ca77b9ce1c3
  sha: 5ec7c5b67678287d2eb30b98ca2707993a152e78
gaol/gaol-linux64:
  size: 8545336
  object_id: 512c442f-da94-4fd0-a882-c6b425f38b47
  sha: 2a0f3a900e37ba04fcbdaf1a2880aede04b1d4d8
gotcha/gotcha-linux-amd64:
  size: 6935960
  object_id: 2db875ec-7624-4009-8478-6565909c913e
  sha: d0978333942b48a00e8e901c5e86584b2d1f1158
hatop/hatop:
  size: 72429
  object_id: 9d096d6c-5f55-456a-8387-39d45f3d7a0e
  sha: daddb3f13a70d4e2fa0802333c2e13468635171f
jq/jq-linux64:
  size: 3027945
  object_id: babe6a62-2740-4aa8-9e03-fe1437169669
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
mysql/mariadb-10.3.4.tar.gz:
  size: 70850293
  object_id: d6c4d61a-e7a6-4ea3-5bd6-28030e579ece
  sha: 71eb4e39ed7dda36213bd761a93098c9a7dc2903
nats/nats-1.0.2-linux-x86_64.tar.gz:
  size: 1976167
  object_id: 9530f4aa-fcca-43d2-af55-34b8b44a728c
  sha: a47897ac81b83d7e72344ef0c58b90dc9db036c5
netsniff-ng/libcli-1.9.7.tar.gz:
  size: 29557
  object_id: efe03ced-bed3-49a5-b61d-b93e346b8eba
  sha: 0bf27f3f9e0f5284e04663afe3f865136b0d5f30
netsniff-ng/libmnl-1.0.3.tar.bz2:
  size: 337375
  object_id: 5bd60d2f-3dca-4220-8124-4ec3ee881743
  sha: c27e25f67c6422ebf893fc3a844af8085a1c5b63
netsniff-ng/libnet-1.1.6.tar.gz:
  size: 1202970
  object_id: 6f374800-a71d-49a0-8cb2-79066f736626
  sha: dffff71c325584fdcf99b80567b60f8ad985e34c
netsniff-ng/libnetfilter_conntrack-1.0.5.tar.bz2:
  size: 418516
  object_id: 0ec53245-ce87-4c3d-88a8-cf9b17f34c1e
  sha: 9aed8733d98af39d57fffd929c2bea70f1dcba06
netsniff-ng/libnfnetlink-1.0.1.tar.bz2:
  size: 320641
  object_id: 47f5296f-b253-41aa-8d4a-5a570a5f2f06
  sha: 27ae2dfbd976e28cb7a417f9e946c901f512dd9a
netsniff-ng/libnl-3.2.25.tar.gz:
  size: 832513
  object_id: 633075cf-8bf6-46c9-8f58-aacc93886d5e
  sha: b7a4981f7edf7398256d35fd3c0b87bc84ae27d1
netsniff-ng/libpcap-1.7.4.tar.gz:
  size: 663021
  object_id: f4c31382-6054-40bd-934d-039706d08071
  sha: 3f31a7706c1487fca36b8379e511965a8d7cbd70
netsniff-ng/libsodium-1.0.8.tar.gz:
  size: 1794750
  object_id: c3df5d17-b234-4a3d-b747-270f45f764b4
  sha: 3d53b827da88d6c2e391fb377bddcd592515ab79
netsniff-ng/nacl-20110221.tar.bz2:
  size: 163415
  object_id: 177d6a76-70d7-44c5-b1ba-9db1373e7c5d
  sha: 6007a6aee249f5a534ec53fddfc364601fba9629
netsniff-ng/ncurses-5.9.tar.gz:
  size: 2826473
  object_id: c32c9ee1-cdb9-478f-a6d2-1b193e670010
  sha: 3e042e5f2c7223bffdaac9646a533b8c758b65b5
netsniff-ng/netsniff-ng-0.6.0.tar.gz:
  size: 719687
  object_id: 515d6e69-363d-45e8-912d-f9567e5fd464
  sha: 0fe01f378190ce7c64c1b2022f9c47060c49885f
netsniff-ng/userspace-rcu-0.9.1.tar.bz2:
  size: 468197
  object_id: d0749b45-feb3-4bb4-bd0c-3e7096569e51
  sha: ca1b603655c3c5bf5d5b6254117999e3ae5f6751
nload/nload-0.7.4.tar.gz:
  size: 151005
  object_id: fe9d2165-bca8-48ff-6f88-79b628070039
  sha: bb0a168c93c588ad4fd5e3a653b3620b79ada1e8
nmap/nmap-7.60.tar.bz2:
  size: 10394925
  object_id: 3e10ab46-3468-4af6-629b-308bd7923885
  sha: 5d36a55ce772ec24f7f50ab52780f932ee20529f
postgresql/postgresql-10.3.tar.gz:
  size: 26357593
  object_id: ca0eb3ce-8b0c-4ec8-7c47-be7c2adb6a1c
  sha: e9431b0019c026927065b8c476fdf92eeebd00aa
redis/redis-3.0.7.tar.gz:
  size: 1375200
  object_id: f048dc59-c299-4c46-a631-4bb14da326db
  sha: e56b4b7e033ae8dbf311f9191cf6fdf3ae974d1c
safe/safe-linux-amd64:
  size: 8244296
  object_id: 070215bd-1490-452b-a09d-77226a3e3832
  sha: 0b9c713ae7ada486e92161de401e251e0b1f4bd9
screen/screen-4.6.2.tar.gz:
  size: 845210
  object_id: 9a562477-9597-47ee-42d3-f1a3916801eb
  sha: 0434d4c45d0b5bb339551511e10a9b2c4ec6a789
spruce/spruce-linux-amd64:
  size: 11885019
  object_id: 03db74bf-f66d-4608-5610-40d7d6c9dcb4
  sha: sha256:4071465c48c8e9060a7f56f33ea83b0b2abdf762d84aea36c1f5478db20ad811
tcptrace/tcptrace:
  size: 2983
  object_id: 0975577c-b183-4e7f-bb13-8db0f1e49361
  sha: 1209e7f64081c4edcf067927e09587aa351bef4d
tree/tree-1.7.0.tgz:
  size: 47082
  object_id: 0206d042-9017-4118-ab4d-a6c79278d0e0
  sha: 35bd212606e6c5d60f4d5062f4a59bb7b7b25949
tshark/glib-2.45.8.tar.xz:
  size: 7188216
  object_id: 833a983c-402a-47de-b2ec-34622b701239
  sha: a25590b540251f9ed4a56ea2837d28071bddfa5a
tshark/libffi-3.2.1.tar.gz:
  size: 940837
  object_id: a7ca9dbe-a0ec-48c8-a8bd-6fa71ccd07b9
  sha: 280c265b789e041c02e5c97815793dfc283fb1e6
tshark/libpcap-1.6.2.tar.gz:
  size: 651237
  object_id: 3e8879fc-f96c-41a6-a10f-41d0bd3c2ef4
  sha: 7efc7d56f4959de8bb33a92de2e15d92105eac32
tshark/wireshark-2.0.3.tar.bz2:
  size: 31110988
  object_id: e4170c85-e311-444f-81ac-df48b8f5054e
  sha: 9805d62b4fb108cc1e755d8c47f8c1e21eee8b73
vault/vault_0.5.2_linux_amd64.zip:
  size: 8966609
  object_id: bb2ac4f2-5ab2-463b-a51e-3f6f05343aed
  sha: c4d9ec11309877885bab68d3a1df6c80f63a8159
veritas/veritas-47c19f8:
  size: 12270832
  object_id: 7e2f5aaa-fc23-4b71-85be-50bd4947335e
  sha: 6c1ae8605fc58848fee1c6ea80571dc93be52173
